[book]
authors = ["ArendGr"]
language = "en"
multilingual = false
src = "src"
title = "Process and safety"

[preprocessor.plantuml]
plantuml-cmd="http://localhost:8181"

[output.html]
default-theme ="Coal"


